services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    restart: unless-stopped
    networks:
      - internal-net
    env_file:
      - .env
    ports:
      - 3307:3306

  wordpress:
    depends_on:
      - db
    image: wordpress:6.5.3
    networks:
      - internal-net
      - wordpress-net
    ports:
      - 8081:80
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - VIRTUAL_PORT=8081

networks:
  internal-net:
  wordpress-net:
    name: ${NETWORK:-wordpress-net}
    external: ${USE_EXTERNAL_NETWORK:-false}
