version: '3'

services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    ports:
      - 3306:3306

  composer:
    image: composer
    restart: no
    volumes:
      - ./incomaker:/project
    working_dir: /project
    command: bash -c "composer install"

  wordpress:
    depends_on:
      - composer
      - db
    image: wordpress
    volumes:
      - ./incomaker:/var/www/html/wp-content/plugins/incomaker
    ports:
      - 8081:80
    restart: unless-stopped
    environment:
      - WORDPRESS_DEBUG=true
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_USERNAME=admin
      - WORDPRESS_PASSWORD=password
