### With pretty URLs
GET http://fs.incomaker.com:8081/wp-json/incomaker/v210/feed/?type=product&key=34492d88-723e-42c9-9a95-b808deae321c

### Without pretty URLs
GET http://fs.incomaker.com:8081/?rest_route=/incomaker/v210/feed/&type=product&key=34492d88-723e-42c9-9a95-b808deae321c

### Coupons
GET http://fs.incomaker.com:8081/wp-json/incomaker/v210/feed/?type=coupon&key=34492d88-723e-42c9-9a95-b808deae321c

### Orders
GET http://fs.incomaker.com:8081/wp-json/incomaker/v210/feed/?type=order&key=34492d88-723e-42c9-9a95-b808deae321c

### Products
GET http://fs.incomaker.com:8081/wp-json/incomaker/v210/feed/?type=product&key=34492d88-723e-42c9-9a95-b808deae321c
